# lightweight python image 
FROM python:3.9-slim

#Set the working directory
WORKDIR /app

# Copy the requeriments file and install the dependencies
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# COPY the backend code
COPY backend/ .

# Expose the port the app runs in
EXPOSE 5000

# Command to run the application
CMD ["python", "app.py"]